import { timestamp, varchar } from "drizzle-orm/pg-core";

/**
 * Shared column builders. IDs are 32-char hex UUIDs generated by the
 * application (the Python API uses uuid4().hex); the database never generates
 * them, so both writers agree on the format.
 */
export const id = () => varchar("id", { length: 32 }).primaryKey();

export const createdAt = () =>
  timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull();
