/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Elements
         * @description The element catalog for the campaign form, with per-engine support.
         *
         *     Espresso support means a pseudopotential is present in the configured
         *     pseudo_dir (fetch with `python -m gibbs.pseudos <El>`).
         */
        get: operations["list_elements_campaigns_elements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Campaign */
        post: operations["start_campaign_campaigns__campaign_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Campaign */
        post: operations["pause_campaign_campaigns__campaign_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Calculations */
        get: operations["list_calculations_campaigns__campaign_id__calculations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_campaigns__campaign_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/agent-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Events */
        get: operations["list_agent_events_campaigns__campaign_id__agent_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/surrogate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Surrogate View
         * @description Latest surrogate curve plus the measured points it was trained on.
         */
        get: operations["get_surrogate_view_campaigns__campaign_id__surrogate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/structures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Structures */
        get: operations["list_structures_campaigns__campaign_id__structures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/hull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hull View
         * @description Formation-energy hull view for alloy campaigns: measurements, predictions, hull.
         */
        get: operations["get_hull_view_campaigns__campaign_id__hull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Final scientific report (plan section 16). Persisted at completion;
         *     generated on the fly for campaigns still in progress.
         */
        get: operations["get_report_campaigns__campaign_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidates
         * @description Ranked candidates for property campaigns (plan section 14).
         */
        get: operations["get_candidates_campaigns__campaign_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/phase-diagram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Phase Diagram
         * @description T-x phase-diagram view: per-slice boundary estimates, curves, measurements.
         */
        get: operations["get_phase_diagram_campaigns__campaign_id__phase_diagram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-Sent Events: live agent actions, job lifecycle, model updates.
         */
        get: operations["stream_events_campaigns__campaign_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{calculation_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calculation Log
         * @description Raw engine log artifact (e.g. the pw.x output) for the run inspector.
         */
        get: operations["get_calculation_log_calculations__calculation_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{calculation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calculation */
        get: operations["get_calculation_calculations__calculation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculations/{calculation_id}/retries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Retries */
        get: operations["get_retries_calculations__calculation_id__retries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Benchmarks */
        get: operations["list_benchmarks_benchmarks_get"];
        put?: never;
        /** Create Benchmark */
        post: operations["create_benchmark_benchmarks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmarks/{benchmark_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmark */
        get: operations["get_benchmark_benchmarks__benchmark_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Copilot Status
         * @description Whether the copilot can answer (its model's provider key is configured).
         */
        get: operations["copilot_status_copilot_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chats
         * @description The user's chats, most recently active first.
         */
        get: operations["list_chats_copilot_chats_get"];
        put?: never;
        /** Create Chat */
        post: operations["create_chat_copilot_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_copilot_chats__chat_id__get"];
        put?: never;
        post?: never;
        /** Delete Chat */
        delete: operations["delete_chat_copilot_chats__chat_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send a message and stream the copilot's reply as SSE events:
         *     `text` {delta}, `tool_call` {id,name,args}, `tool_result` {id,name,ok},
         *     `patch` {patch,rationale} (a form proposal), `done` {transcript}, `error` {detail}.
         *
         *     The user row is written first; the assistant row and its tool calls are
         *     written when the run completes, so a failed run leaves only the question.
         */
        post: operations["send_message_copilot_chats__chat_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentEventRead */
        AgentEventRead: {
            /** Id */
            id: string;
            /** Agent Run Id */
            agent_run_id: string | null;
            /** Campaign Id */
            campaign_id: string;
            /** Event Type */
            event_type: string;
            /** Hypothesis */
            hypothesis: string | null;
            /** Reasoning Summary */
            reasoning_summary: string | null;
            /** Action */
            action: string | null;
            /** Tool Name */
            tool_name: string | null;
            /** Tool Input */
            tool_input: {
                [key: string]: unknown;
            } | null;
            /** Tool Output Reference */
            tool_output_reference: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AlloyHullView
         * @description Everything the dashboard needs to draw the formation-energy hull.
         */
        AlloyHullView: {
            /** Campaign Id */
            campaign_id: string;
            /** Model Version */
            model_version: number | null;
            /** Loocv Rmse */
            loocv_rmse: number | null;
            /** Points */
            points: components["schemas"]["HullPoint"][];
            /** Hull X */
            hull_x: number[];
            /** Hull E */
            hull_e: number[];
            /** Stable Labels */
            stable_labels: string[];
            /** Endpoints Measured */
            endpoints_measured: boolean;
            /**
             * Energy Unit
             * @default eV/atom
             */
            energy_unit: string;
            /** Engine */
            engine?: string | null;
        };
        /** BenchmarkCreate */
        BenchmarkCreate: {
            /** @default ising */
            problem: components["schemas"]["BenchmarkProblem"];
            /**
             * Strategies
             * @default [
             *       "random",
             *       "grid",
             *       "uncertainty"
             *     ]
             */
            strategies: components["schemas"]["StrategyName"][];
            /**
             * Budget
             * @default 12
             */
            budget: number;
            /**
             * Seeds
             * @default [
             *       1,
             *       2,
             *       3
             *     ]
             */
            seeds: number[];
            /**
             * Lattice Size
             * @default 16
             */
            lattice_size: number;
            /**
             * Temperature Min
             * @default 1.5
             */
            temperature_min: number;
            /**
             * Temperature Max
             * @default 3.5
             */
            temperature_max: number;
        };
        /**
         * BenchmarkProblem
         * @enum {string}
         */
        BenchmarkProblem: "ising" | "alloy" | "fcc" | "phase" | "property";
        /** BenchmarkRead */
        BenchmarkRead: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Results */
            results: {
                [key: string]: unknown;
            }[] | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** CalculationRead */
        CalculationRead: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Structure Id */
            structure_id?: string | null;
            /** Calculation Type */
            calculation_type: string;
            /** Engine */
            engine: string;
            /** Status */
            status: string;
            /** Input Parameters */
            input_parameters: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            } | null;
            /** Failure Category */
            failure_category: string | null;
            /** Failure Metadata */
            failure_metadata: {
                [key: string]: unknown;
            } | null;
            /** Retry Of */
            retry_of: string | null;
            /** Changed Parameters */
            changed_parameters: {
                [key: string]: unknown;
            } | null;
            /** Reason For Change */
            reason_for_change: string | null;
            /** Resolution */
            resolution: string | null;
            /** Stdout Artifact */
            stdout_artifact?: string | null;
            /** Stderr Artifact */
            stderr_artifact?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** CampaignCreate */
        CampaignCreate: {
            /** Name */
            name: string;
            /** @default ising_v0 */
            problem_type: components["schemas"]["ProblemType"];
            /**
             * Objective
             * @description Defaults to the problem's canonical objective when empty.
             * @default
             */
            objective: string;
            /** Composition Min */
            composition_min?: number | null;
            /** Composition Max */
            composition_max?: number | null;
            /**
             * Composition Slices
             * @description Composition slices for phase-diagram campaigns (each strictly between 0 and 1; default [0.25, 0.5, 0.75]).
             */
            composition_slices?: number[] | null;
            /** @default agent */
            strategy: components["schemas"]["StrategyName"];
            /**
             * Elements
             * @description The two element symbols [A, B] for FCC alloy problems (fcc_v2, phase_v2, dft_v3, property_v3); composition x is the fraction of B. Default Ni-Al. EMT supports Al, Cu, Ag, Au, Ni, Pd, Pt; Quantum ESPRESSO needs a pseudopotential per element.
             */
            elements?: string[] | null;
            /**
             * @description Energy/property engine for property_v3 campaigns: hidden synthetic oracle (benchmarkable) or EMT (real classical potential).
             * @default hidden
             */
            property_engine: components["schemas"]["PropertyEngine"];
            /**
             * Temperature Threshold
             * @description Property campaigns: candidates must stay ordered below this T (K).
             * @default 1200
             */
            temperature_threshold: number;
            /**
             * @description Energy engine for dft_v3 campaigns: 'emt' (fast classical potential) or 'espresso' (real Quantum ESPRESSO DFT; needs pw.x + pseudos).
             * @default emt
             */
            dft_engine: components["schemas"]["DftEngine"];
            /**
             * Temperature Min
             * @default 1.5
             */
            temperature_min: number;
            /**
             * Temperature Max
             * @default 3.5
             */
            temperature_max: number;
            /**
             * Lattice Size
             * @default 24
             */
            lattice_size: number;
            /**
             * Simulation Budget
             * @default 20
             */
            simulation_budget: number;
            /**
             * Target Uncertainty
             * @description Stop early when the Tc-estimate std drops below this value.
             */
            target_uncertainty?: number | null;
            /**
             * Failure Rate
             * @description Injected simulation-failure probability (for failure-recovery demos).
             * @default 0
             */
            failure_rate: number;
        };
        /** CampaignRead */
        CampaignRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Objective */
            objective: string;
            /** Problem Type */
            problem_type: string;
            /** Strategy */
            strategy: string;
            /**
             * Elements
             * @default []
             */
            elements: string[];
            /** Temperature Min */
            temperature_min: number;
            /** Temperature Max */
            temperature_max: number;
            /** Composition Min */
            composition_min?: number | null;
            /** Composition Max */
            composition_max?: number | null;
            /** Lattice Size */
            lattice_size: number;
            /** Simulation Budget */
            simulation_budget: number;
            /** Simulations Used */
            simulations_used: number;
            /** Target Uncertainty */
            target_uncertainty: number | null;
            /** Failure Rate */
            failure_rate: number;
            status: components["schemas"]["CampaignStatus"];
            /** Stopping Rationale */
            stopping_rationale: string | null;
            /** Engine */
            engine?: string | null;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CampaignReport */
        CampaignReport: {
            /** Campaign Id */
            campaign_id: string;
            /** Generated At */
            generated_at: string;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /** Status */
            status: string;
            /** Strategy */
            strategy: string;
            /** Problem Type */
            problem_type: string;
            /** Budget */
            budget: {
                [key: string]: unknown;
            };
            /** Engines */
            engines: string[];
            /** Model */
            model: {
                [key: string]: unknown;
            };
            /** Key Results */
            key_results: string[];
            /** Recommendation */
            recommendation: {
                [key: string]: unknown;
            };
            /** Stopping Rationale */
            stopping_rationale: string | null;
            /** Failures */
            failures: {
                [key: string]: unknown;
            };
            /** Decision Trail */
            decision_trail: {
                [key: string]: unknown;
            }[];
            /** Limitations */
            limitations: string[];
            /** Narrative */
            narrative: string | null;
            /** Llm Narrative */
            llm_narrative?: string | null;
        };
        /**
         * CampaignStatus
         * @enum {string}
         */
        CampaignStatus: "CREATED" | "RUNNING" | "PAUSED" | "COMPLETED" | "FAILED";
        /**
         * CampaignSurrogateView
         * @description Everything the dashboard needs to draw chi(T) with uncertainty.
         */
        CampaignSurrogateView: {
            /** Campaign Id */
            campaign_id: string;
            /** Model Version */
            model_version: number | null;
            /** Temperatures */
            temperatures: number[];
            /** Mean */
            mean: number[];
            /** Std */
            std: number[];
            /** Measured Temperatures */
            measured_temperatures: number[];
            /** Measured Values */
            measured_values: number[];
            /** Measured Errors */
            measured_errors: number[];
            /** Measured Calculation Ids */
            measured_calculation_ids: string[];
            /** Tc Mean */
            tc_mean: number | null;
            /** Tc Std */
            tc_std: number | null;
        };
        /** CandidateRead */
        CandidateRead: {
            /** Label */
            label: string;
            /** X */
            x: number;
            /** E Form */
            e_form: number;
            /** E Form Std */
            e_form_std: number;
            /** E Above Hull */
            e_above_hull: number;
            /** Bulk Modulus */
            bulk_modulus: number;
            /** Bulk Modulus Std */
            bulk_modulus_std: number;
            /** Measured */
            measured: boolean;
            /** Stable 0K */
            stable_0k: boolean;
            /** Stability At Threshold */
            stability_at_threshold: string;
            /** Score */
            score: number;
        };
        /**
         * CandidatesView
         * @description Plan section 14: the ranked candidate table.
         */
        CandidatesView: {
            /** Campaign Id */
            campaign_id: string;
            /** Temperature Threshold */
            temperature_threshold: number;
            /** Model Version */
            model_version: number | null;
            /** Top Candidate Label */
            top_candidate_label: string | null;
            /** Candidates */
            candidates: components["schemas"]["CandidateRead"][];
        };
        /**
         * CopilotChatCreate
         * @description A new chat. The id (uuid) is generated by the database.
         */
        CopilotChatCreate: {
            /** Title */
            title?: string | null;
        };
        /** CopilotChatRead */
        CopilotChatRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Transcript */
            transcript: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CopilotChatSummary */
        CopilotChatSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CopilotMessageCreate */
        CopilotMessageCreate: {
            /** Content */
            content: string;
            context?: components["schemas"]["CopilotPageContext"];
        };
        /** CopilotPageContext */
        CopilotPageContext: {
            /**
             * Page
             * @default other
             */
            page: string;
            /** Campaign Id */
            campaign_id?: string | null;
            /** Form */
            form?: {
                [key: string]: unknown;
            } | null;
        };
        /** CopilotStatus */
        CopilotStatus: {
            /** Available */
            available: boolean;
            /** Model */
            model: string;
            /** Reason */
            reason: string;
        };
        /**
         * DftEngine
         * @enum {string}
         */
        DftEngine: "emt" | "espresso";
        /**
         * ElementRead
         * @description One entry of the element catalog offered by the campaign form.
         */
        ElementRead: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Atomic Number */
            atomic_number: number;
            /** Structure */
            structure: string;
            /** Fcc Native */
            fcc_native: boolean;
            /** A Fcc */
            a_fcc: number;
            /** Engines */
            engines: {
                [key: string]: boolean;
            };
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HullPoint */
        HullPoint: {
            /** Structure Id */
            structure_id: string;
            /** Label */
            label: string;
            /** X */
            x: number;
            /** E Form */
            e_form?: number | null;
            /** E Form Std */
            e_form_std?: number | null;
            /**
             * Measured
             * @default false
             */
            measured: boolean;
            /**
             * Predicted Stable
             * @default false
             */
            predicted_stable: boolean;
        };
        /**
         * PhaseDiagramView
         * @description Everything the dashboard needs to draw the T-x phase diagram.
         */
        PhaseDiagramView: {
            /** Campaign Id */
            campaign_id: string;
            /** Model Version */
            model_version: number | null;
            /** Temperature Min */
            temperature_min: number;
            /** Temperature Max */
            temperature_max: number;
            /** Slices */
            slices: components["schemas"]["PhaseSliceView"][];
        };
        /** PhaseMeasurementView */
        PhaseMeasurementView: {
            /** Calculation Id */
            calculation_id: string;
            /** Temperature */
            temperature: number;
            /** Heat Capacity */
            heat_capacity: number;
            /** Heat Capacity Err */
            heat_capacity_err: number;
            /** Sro */
            sro: number;
        };
        /** PhaseSliceView */
        PhaseSliceView: {
            /** X */
            x: number;
            /** Tc Mean */
            tc_mean?: number | null;
            /** Tc Std */
            tc_std?: number | null;
            /**
             * Tc Edge Pinned
             * @default false
             */
            tc_edge_pinned: boolean;
            /**
             * Curve T
             * @default []
             */
            curve_t: number[];
            /**
             * Curve Mean
             * @default []
             */
            curve_mean: number[];
            /**
             * Curve Std
             * @default []
             */
            curve_std: number[];
            /**
             * Measured
             * @default []
             */
            measured: components["schemas"]["PhaseMeasurementView"][];
        };
        /**
         * ProblemType
         * @enum {string}
         */
        ProblemType: "ising_v0" | "alloy_v1" | "fcc_v2" | "phase_v2" | "dft_v3" | "property_v3";
        /**
         * PropertyEngine
         * @enum {string}
         */
        PropertyEngine: "hidden" | "emt" | "espresso";
        /** StartResponse */
        StartResponse: {
            /** Campaign Id */
            campaign_id: string;
            status: components["schemas"]["CampaignStatus"];
            /** Agent Run Id */
            agent_run_id?: string | null;
        };
        /**
         * StrategyName
         * @enum {string}
         */
        StrategyName: "agent" | "random" | "grid" | "uncertainty";
        /** StructureRead */
        StructureRead: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Label */
            label: string;
            /** Chemical Formula */
            chemical_formula: string;
            /** Composition */
            composition: number;
            /** N Sites */
            n_sites: number;
            /** Occupations */
            occupations: number[][];
            /** Shape */
            shape: number[];
            /** Lattice */
            lattice?: number[][] | null;
            /** Positions */
            positions?: number[][] | null;
            /** Atomic Numbers */
            atomic_numbers?: number[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SurrogateModelRead */
        SurrogateModelRead: {
            /** Id */
            id: string;
            /** Campaign Id */
            campaign_id: string;
            /** Type */
            type: string;
            /** Version */
            version: number;
            /** Training Calculation Ids */
            training_calculation_ids: string[];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Validation Metrics */
            validation_metrics: {
                [key: string]: unknown;
            };
            /** Artifact */
            artifact: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_campaigns_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"][];
                };
            };
        };
    };
    create_campaign_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_elements_campaigns_elements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementRead"][];
                };
            };
        };
    };
    get_campaign_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_campaign_campaigns__campaign_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_campaign_campaigns__campaign_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calculations_campaigns__campaign_id__calculations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_campaigns__campaign_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurrogateModelRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_events_campaigns__campaign_id__agent_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_surrogate_view_campaigns__campaign_id__surrogate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSurrogateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_structures_campaigns__campaign_id__structures_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hull_view_campaigns__campaign_id__hull_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlloyHullView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_campaigns__campaign_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidates_campaigns__campaign_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_phase_diagram_campaigns__campaign_id__phase_diagram_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseDiagramView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_campaigns__campaign_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calculation_log_calculations__calculation_id__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calculation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calculation_calculations__calculation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calculation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_retries_calculations__calculation_id__retries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calculation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_benchmarks_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRead"][];
                };
            };
        };
    };
    create_benchmark_benchmarks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_benchmark_benchmarks__benchmark_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                benchmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_status_copilot_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotStatus"];
                };
            };
        };
    };
    list_chats_copilot_chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotChatSummary"][];
                };
            };
        };
    };
    create_chat_copilot_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotChatCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_copilot_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotChatRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_copilot_chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_copilot_chats__chat_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
